services:
  portal-db:
    image: postgres:18
    container_name: portal-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portal
    ports:
      - "5432:5432"
    volumes:
      - portal-db-data:/var/lib/postgresql

volumes:
  portal-db-data:
